# Use root/example as user/password credentials
version: '3.1'

services:
  order-service:
    image: order-service:1.0
#    restart: always
#    ports:
#      - "3307:3306"
    # 0번 랜덤포트는 port 설정 의미없음
    environment:
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.base-url: http://zipkin-zipkin-1:9411
      spring.datasource.url: jdbc:mariadb://mariadb-server:3306/mydb
      eureka.client.service-url.defaultZone: http://service-discovery:8761/eureka/
      management.zipkin.tracing.endpoint: http://zipkin-zipkin-1:9411/api/v2/spans
#      MARIADB_ROOT_PASSWORD: test1357
#      MARIADB_USER: example-user
#      MARIADB_PASSWORD: test1357
#      MARIADB_DATABASE: mydb
    networks:
      ecommerce-network:

networks:
  ecommerce-network:
    external: true