server:
  port: 8888

spring:
  #  profiles:
  #    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
        # 윈도우 config 로컬 파일의 경로
        #          search-locations: file:///C://LgCns//work//git-local-repo
        git: #default
          # uri: https://github.com/joneconsulting/spring-cloud-config
          # 나의 깃 레포지토리 config 경로
          uri: https://github.com/minnnseokk/spring-cloud-config
          #          uri: file:///C://LgCns//work//git-local-repo
          default-label: master
        #          username: <github-id>
        #          password: <gihub-accessToken>
        bootstrap: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics
